### PR TITLE
add github-2017-emoji-first stack

### PR DESCRIPTION
**Pull request by junosuarez**

### CODE REVIEW

**Comment by junosuarez** [comment]
gh pages at https://jsdnxx.github.io/system-font-stack-experiments/emoji.html

so this is interesting, but it also intercepts some non-emoji characters that are probably *not* what we want. I seem to recall github doing some html replacement to have a special class for known-emoji characters, which I imaging would have a different font stack.

on chrome / macos (note the numbers 2017 on the first row):
image


here's another PR i made showing segoe ui on windows:
https://github.com/rickycodes/emoji-picker/pull/1

/cc @hkjorgensen

**Comment by alanhogan** [comment]
@jsdnxx @hkjorgensen Hey! Thanks. I didn't see this until now! Somehow I haven't been watching 👁 my own repo! Sigh.

In the mean time, I had already gone through and tried this sort of a reordering at Nathan's request, so I called it `nathan-1` in the code, although this was specifically for Segoe only. And basically it was disappointing because it changes the font used for actual text, so it's no longer Segoe. It's not a viable font stack for general text, although if we isolated and wrapped emoji in little `<span>`s with their own font stack, such a technique might be more useful?

**Comment by alanhogan** [comment]
wow so the github emoji technique seems “complicated” to put it mildly:

screen shot 2017-03-09 at 6 41 04 pm

```html
<g-emoji alias="eye" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f441.png" ios-version="9.1">👁</g-emoji>
```

that isn't too crazy i guess, but this is: 

```css
@media only screen and (-webkit-min-device-pixel-ratio: 2), not all, not all, not all, only screen and (min-resolution: 192dpi), only screen and (min-resolution: 2dppx) {
  body.emoji-size-boost g-emoji {
    margin-right: 0;
    font-size: 21px;
  }
}
```

I am imagining GitHub clutching its knees, rocking back and forth, and repeating _**not all, not all, not all**_ slowly to itself in the dark

**Comment by junosuarez** [comment]
> isolated and wrapped emoji in little <span>s with their own font stack

this seems to be the approach I see on sites I use in the wild - in many cases, I think it's for image-based fallbacks, but it seems like it would also give us better font-stack options (and sizing, and shown by the github example) even with system emoji.

**Comment by alanhogan** [comment]
100%, @jsdnxx.

**Comment by alanhogan** [comment]
system font results via valentin - with nathan-1 emoji suite 2017-03-03 at 4 07 59 pm

Here is a screen shot @vcekov kindly provided from his Windows 10 device using a variant of the GitHub font stack but with “Segoe Emoji” ahead of “Segoe,” the “Nathan (1)” experiment. Pretty clearly, it is a win for emojis but a huge loss in terms of control over the actual text.

(Clockwise from top-left, it looks like Firefox, Edge, IE, Chrome.)

**Comment by alanhogan** [comment]
well, there is one more downside which is that any inclusion of emoji fonts in the font stack tends to make browsers show symbols as emojis even when they should not be. (for reference see https://stackoverflow.com/questions/42679712/why-does-the-red-heart-emoji-require-two-code-points-but-the-other-colored-hear/42680595#42680595 or http://randomguy32.de/unicode/charts/standardized-variants/#emoji)

**Comment by alanhogan** [comment]
(Clockwise from top-left, it looks like Firefox, Edge, IE, Chrome.)

**Comment by junosuarez** [comment]
@alanhogan if you ever want win10 screenshots, we have a work-owned physical win10 device in the portland office, let us know

**Comment by alanhogan** [comment]
We have one here but it's a tablet and annoying and hard to use and get screen shots off. It also doesn’t have IE, just Edge.

Does your device have IE11?

— Alan

**Comment by junosuarez** [comment]
just Edge. Is there a way to have IE11 installed in parallel? Or just with the IE Compatibility Images in a VM?

**Comment by junosuarez** [comment]
(It probably makes sense for you to ask IT for a machine representative of something a sizable chunk of your users use. We got a Thinkpad T440s.)

**Comment by alanhogan** [comment]
Agreed, I should do that!

I’m not a Windows expert, but I thought Microsoft explicitly shipped both browsers together since Edge was first introduced. Maybe I’m wrong, or maybe they stopped.

— Alan

**Pull request closed without merging**
